# Generated by Django 5.2.6 on 2026-04-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City name (from reference or free text).', max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Height in centimeters.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Display nickname (latin letters + digits).', max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (optional).', max_digits=5, null=True),
        ),
    ]
