# Generated by Django 5.2.6 on 2026-04-22 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_password_reset_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'verbose_name': 'Код сброса пароля', 'verbose_name_plural': 'Коды сброса пароля'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'Социальный аккаунт', 'verbose_name_plural': 'Социальные аккаунты'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Справочник или произвольно.', max_length=128, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другое')], default='', max_length=16, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Латиница и цифры.', max_length=64, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code_hash',
            field=models.CharField(max_length=128, verbose_name='Хэш кода'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('vk', 'VK'), ('google', 'Google'), ('apple', 'Apple')], max_length=16, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider_user_id',
            field=models.CharField(max_length=255, verbose_name='ID пользователя у провайдера'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
