# Generated by Django 5.2.6 on 2026-05-03 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chronic_diseases',
            field=models.TextField(blank=True, default='', verbose_name='Хронические заболевания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='had_covid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Переболели Covid-19'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_code_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Пин-код (хэш)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='useful_tips_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписка на полезные советы'),
        ),
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=64, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_of', to=settings.AUTH_USER_MODEL, verbose_name='Привязанный профиль')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_owned_links', to=settings.AUTH_USER_MODEL, verbose_name='Основной пользователь')),
            ],
            options={
                'verbose_name': 'Связь семейных аккаунтов',
                'verbose_name_plural': 'Связи семейных аккаунтов',
                'constraints': [models.UniqueConstraint(fields=('owner', 'member'), name='uniq_family_owner_member')],
            },
        ),
    ]
