# Generated by Django 5.0.7 on 2026-06-16 04:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('tier', models.CharField(choices=[('free_trial', 'Пробный период'), ('free', 'Бесплатный'), ('standard', 'Стандарт'), ('premium', 'Премиум')], max_length=16, verbose_name='Уровень')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (₽)')),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Пусто — без срока (бессрочно).', null=True, verbose_name='Срок действия (дней)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_purchasable', models.BooleanField(default=True, verbose_name='Можно купить')),
                ('is_auto_trial', models.BooleanField(default=False, help_text='Один раз на аккаунт; повторно не выдаётся.', verbose_name='Выдаётся при регистрации')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='max_disease_records, max_cabinet_items, extended_ai, calendar_ai, …', verbose_name='Лимиты и возможности')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (₽)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус')),
                ('robokassa_inv_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='InvId Robokassa')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='Описание')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('callback_payload', models.JSONField(blank=True, default=dict, verbose_name='Данные callback')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.tariffplan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_trial_used', models.BooleanField(default=False, verbose_name='Пробный период использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Биллинг-профиль',
                'verbose_name_plural': 'Биллинг-профили',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('superseded', 'Заменена')], default='active', max_length=16, verbose_name='Статус')),
                ('source', models.CharField(choices=[('auto_trial', 'Авто trial'), ('auto_free', 'Авто Free'), ('payment', 'Оплата'), ('admin', 'Админ')], max_length=16, verbose_name='Источник')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('expiry_warnings_sent', models.JSONField(blank=True, default=list, verbose_name='Отправленные напоминания (дней до конца)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.payment', verbose_name='Платёж')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.tariffplan', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='billing_pay_user_id_c9be81_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='billing_pay_status_bc3ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status', '-expires_at'], name='billing_use_user_id_c4950f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'expires_at'], name='billing_use_status_24ce46_idx'),
        ),
    ]
