# Generated by Django 5.2.6 on 2026-05-03 05:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_bodypart_symptom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdateBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Обновление MedicAi', max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Список изменений')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('send_push', models.BooleanField(default=False, verbose_name='Отправить push (заглушка)')),
            ],
            options={
                'verbose_name': 'Обновление программы',
                'verbose_name_plural': 'Обновления программы',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Город')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RelaxAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gif', 'GIF'), ('video', 'Видео')], max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='relax/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Релакс контент',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
        migrations.CreateModel(
            name='ApiErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ошибка API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Поддержка', max_length=255)),
                ('status', models.CharField(default='open', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат поддержки',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='medic.chatthread')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_url', models.URLField(blank=True, default='')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_rows', to='catalog.drug')),
            ],
            options={
                'verbose_name': 'Аналог лекарства',
            },
        ),
        migrations.CreateModel(
            name='DrugDiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_thread', to='catalog.drug')),
            ],
            options={
                'verbose_name': 'Обсуждение лекарства',
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='medic.drugdiscussionthread')),
            ],
            options={
                'verbose_name': 'Сообщение обсуждения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='catalog.disease')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
            },
        ),
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PsychologyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psych_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вопрос психологу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('query_text', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('answers', models.JSONField(default=dict)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
            },
        ),
        migrations.CreateModel(
            name='UsefulTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useful_tips', to='catalog.disease', verbose_name='Заболевание')),
            ],
            options={
                'verbose_name': 'Полезный совет',
                'verbose_name_plural': 'Полезные советы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserTipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_per_day', models.PositiveSmallIntegerField(default=3, verbose_name='Советов в сутки')),
                ('useful_subscribed', models.BooleanField(default=False, verbose_name='Подписка на полезное')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tip_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки советов',
                'verbose_name_plural': 'Настройки советов',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудит',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='medic_audit_created_4124cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiseaseTipSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_subscribers', to='catalog.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_tip_subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на советы по болезни',
                'unique_together': {('user', 'disease')},
            },
        ),
        migrations.CreateModel(
            name='DrugReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=16)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв на лекарство',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['drug', 'status', '-created_at'], name='medic_drugr_drug_id_b7a735_idx')],
            },
        ),
        migrations.CreateModel(
            name='DrugUserStarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_star_ratings', to='catalog.drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_star_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка лекарства пользователем',
                'constraints': [models.UniqueConstraint(fields=('drug', 'user'), name='uniq_drug_user_star')],
            },
        ),
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pharmacy', 'Аптека'), ('hospital', 'Больница')], max_length=16, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, default='', max_length=512, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон')),
                ('hours_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Часы работы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/', verbose_name='Изображение')),
                ('external_source', models.CharField(blank=True, default='', max_length=32, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Внешний ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='medic.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Мед. учреждение',
                'verbose_name_plural': 'Мед. учреждения',
                'indexes': [models.Index(fields=['kind', 'city', 'name'], name='medic_medic_kind_bcc236_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_user_label', models.CharField(blank=True, default='', max_length=128, verbose_name='Для кого (подпись)')),
                ('kind', models.CharField(choices=[('system', 'Система'), ('hospital', 'Больница'), ('reminder', 'Напоминание'), ('update', 'Обновление'), ('useful', 'Полезное')], default='system', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('link_url', models.URLField(blank=True, default='')),
                ('event_at', models.DateTimeField(blank=True, null=True, verbose_name='Событие / напоминание')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Событие / уведомление',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='medic_notif_recipie_5d7e9d_idx')],
            },
        ),
    ]
