# Generated by GPT-5.2 on 2026-05-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationevent",
            name="subject_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_events_as_subject",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Для кого (профиль)",
                help_text="Опционально: конкретный профиль (семейный аккаунт), к которому относится событие.",
            ),
        ),
        migrations.CreateModel(
            name="UsefulFeedSeen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_seen_at", models.DateTimeField(auto_now=True, verbose_name="Последний просмотр")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="useful_seen",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр «Полезное»",
                "verbose_name_plural": "Просмотры «Полезное»",
            },
        ),
    ]

