# Generated by Django 5.0.7 on 2026-05-08 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0002_notification_subject_and_useful_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='notify_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомить в'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='notify_offsets_min',
            field=models.JSONField(blank=True, default=list, verbose_name='Смещения (мин)'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Для расписанных уведомлений (1 сутки/3ч/2ч/1ч) — ссылка на исходное событие.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_children', to='medic.notificationevent', verbose_name='Родительское событие'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['recipient', 'notify_at'], name='medic_notif_recipie_91f883_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['recipient', 'parent'], name='medic_notif_recipie_4cc1d9_idx'),
        ),
    ]
