# Generated by Django 5.0.7 on 2026-05-26 06:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_bodypart_sort_order'),
        ('medic', '0006_survey_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apierrorlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ошибка API', 'verbose_name_plural': 'Ошибки API'},
        ),
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Аудит', 'verbose_name_plural': 'Журнал аудита'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='chatthread',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Чат поддержки', 'verbose_name_plural': 'Чаты поддержки'},
        ),
        migrations.AlterModelOptions(
            name='discussionpost',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение обсуждения', 'verbose_name_plural': 'Сообщения обсуждений'},
        ),
        migrations.AlterModelOptions(
            name='diseasetipsubscription',
            options={'verbose_name': 'Подписка на советы по болезни', 'verbose_name_plural': 'Подписки на советы по болезни'},
        ),
        migrations.AlterModelOptions(
            name='druganalog',
            options={'verbose_name': 'Аналог лекарства', 'verbose_name_plural': 'Аналоги лекарств'},
        ),
        migrations.AlterModelOptions(
            name='drugdiscussionthread',
            options={'verbose_name': 'Обсуждение лекарства', 'verbose_name_plural': 'Обсуждения лекарств'},
        ),
        migrations.AlterModelOptions(
            name='drugreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв на лекарство', 'verbose_name_plural': 'Отзывы на лекарства'},
        ),
        migrations.AlterModelOptions(
            name='druguserstarrating',
            options={'verbose_name': 'Оценка лекарства пользователем', 'verbose_name_plural': 'Оценки лекарств'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы-ответы (FAQ)'},
        ),
        migrations.AlterModelOptions(
            name='feedbackticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='psychologyinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вопрос психологу', 'verbose_name_plural': 'Вопросы психологу'},
        ),
        migrations.AlterModelOptions(
            name='relaxasset',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Контент «Релакс»', 'verbose_name_plural': 'Контент «Релакс»'},
        ),
        migrations.AlterModelOptions(
            name='searchquerylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'Поисковые запросы'},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'verbose_name': 'Ответ на опрос', 'verbose_name_plural': 'Ответы на опросы'},
        ),
        migrations.AlterField(
            model_name='apierrorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='apierrorlog',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='apierrorlog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='apierrorlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код ответа'),
        ),
        migrations.AlterField(
            model_name='apierrorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(max_length=64, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сообщение сотрудника'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='medic.chatthread', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='title',
            field=models.CharField(blank=True, default='Поддержка', max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='body',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='medic.drugdiscussionthread', verbose_name='Обсуждение'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='diseasetipsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='diseasetipsubscription',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_subscribers', to='catalog.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='diseasetipsubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='diseasetipsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_tip_subs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='druganalog',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_rows', to='catalog.drug', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='druganalog',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название аналога'),
        ),
        migrations.AlterField(
            model_name='druganalog',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='druganalog',
            name='source_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='drugdiscussionthread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='drugdiscussionthread',
            name='drug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_thread', to='catalog.drug', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='drugreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='drugreview',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.drug', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='drugreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='drugreview',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='drugreview',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='drugreview',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='drugreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='druguserstarrating',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_star_ratings', to='catalog.drug', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='druguserstarrating',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Звёзды'),
        ),
        migrations.AlterField(
            model_name='druguserstarrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='druguserstarrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_star_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='catalog.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(max_length=512, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='kind',
            field=models.CharField(choices=[('system', 'Система'), ('hospital', 'Больница'), ('reminder', 'Напоминание'), ('update', 'Обновление'), ('useful', 'Полезное')], default='system', max_length=16, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='link_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='psychologyinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='psychologyinquiry',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='psychologyinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('closed', 'Закрыт')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='psychologyinquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psych_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='relaxasset',
            name='category',
            field=models.CharField(choices=[('gif', 'Гиф-анимация'), ('video', 'Видео'), ('music', 'Музыка')], max_length=16, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='relaxasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='relaxasset',
            name='external_url',
            field=models.URLField(blank=True, default='', verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='relaxasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='relax/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='relaxasset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='relaxasset',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='relaxasset',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='query_text',
            field=models.CharField(max_length=512, verbose_name='Текст запроса'),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='source',
            field=models.CharField(max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='searchquerylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='answers',
            field=models.JSONField(default=dict, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usefultip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='usefultip',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='usefultip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='usertipsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tip_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
