# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medic", "0007_alter_apierrorlog_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="medicalfacility",
            constraint=models.UniqueConstraint(
                condition=models.Q(external_source__gt="", external_id__gt=""),
                fields=("external_source", "external_id"),
                name="uniq_facility_external_source_id",
            ),
        ),
    ]
