# Generated by Django 5.0.7 on 2026-07-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0008_facility_external_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='geo_level',
            field=models.CharField(
                choices=[
                    ('region', 'Область/регион'),
                    ('city', 'Город'),
                    ('district', 'Район'),
                ],
                default='city',
                max_length=16,
                verbose_name='Тип',
            ),
        ),
    ]
