# Generated by Django 5.2.6 on 2026-05-03 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_drugviewlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (если не из справочника)')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Годен до')),
                ('note', models.TextField(blank=True, default='', verbose_name='Заметка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cabinet/', verbose_name='Фото упаковки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_entries', to='catalog.drug', verbose_name='Лекарство из справочника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аптечки',
                'verbose_name_plural': 'Аптечка',
                'ordering': ['-expires_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='cabinet_cab_user_id_ecf094_idx')],
            },
        ),
    ]
