# Generated by Django 5.0.7 on 2026-05-08 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_ids', models.JSONField(default=list, verbose_name='ID симптомов')),
                ('symptoms_text', models.TextField(blank=True, default='', verbose_name='Доп. симптомы (текст)')),
                ('body_part_ids', models.JSONField(default=list, verbose_name='ID частей тела')),
                ('temperature_c', models.FloatField(blank=True, null=True, verbose_name='Температура (°C)')),
                ('blood_pressure', models.CharField(blank=True, default='', max_length=32, verbose_name='Давление')),
                ('result', models.JSONField(verbose_name='Результат (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Диагноз помощника',
                'verbose_name_plural': 'Диагнозы помощника',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='assistant_a_user_id_f71fdb_idx')],
            },
        ),
    ]
