# Generated by Django 5.2.6 on 2026-04-21 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_illness', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('symptoms', models.TextField(blank=True, default='')),
                ('doctor_visit_date', models.DateField(blank=True, null=True)),
                ('doctor_specialty', models.CharField(blank=True, default='', max_length=255)),
                ('doctor_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('procedures', models.TextField(blank=True, default='')),
                ('analyses', models.TextField(blank=True, default='')),
                ('prescription_photo', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='catalog.disease')),
                ('drugs', models.ManyToManyField(blank=True, related_name='records', to='catalog.drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_illness', '-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='history_dis_user_id_a61747_idx'), models.Index(fields=['user', 'date_of_illness'], name='history_dis_user_id_e6850b_idx')],
            },
        ),
    ]
