# Generated by Django 5.2.6 on 2026-04-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaserecord',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='diseaserecord',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='diseaserecord',
            name='doctor_full_name',
        ),
        migrations.RemoveField(
            model_name='diseaserecord',
            name='doctor_specialty',
        ),
        migrations.RemoveField(
            model_name='diseaserecord',
            name='doctor_visit_date',
        ),
        migrations.RemoveField(
            model_name='diseaserecord',
            name='prescription_photo',
        ),
        migrations.RemoveField(
            model_name='diseaserecord',
            name='procedures',
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('result_text', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='analyses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='history.diseaserecord')),
            ],
            options={
                'ordering': ['-taken_date', '-created_at'],
                'indexes': [models.Index(fields=['record', 'taken_date'], name='history_ana_record__5cde99_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, default='', max_length=255)),
                ('doctor_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('medicines_text', models.TextField(blank=True, default='')),
                ('procedures_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_visits', to='history.diseaserecord')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['record', 'visit_date'], name='history_doc_record__49a7cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='history.diseaserecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record', 'created_at'], name='history_pre_record__82208b_idx')],
            },
        ),
    ]
