# Generated by Django 5.2.6 on 2026-04-22 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_disease_options_alter_drug_options_and_more'),
        ('history', '0002_remove_diseaserecord_analyses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-taken_date', '-created_at'], 'verbose_name': 'Анализ', 'verbose_name_plural': 'Анализы'},
        ),
        migrations.AlterModelOptions(
            name='diseaserecord',
            options={'ordering': ['-date_of_illness', '-created_at'], 'verbose_name': 'Запись о болезни', 'verbose_name_plural': 'Записи о болезнях'},
        ),
        migrations.AlterModelOptions(
            name='doctorvisit',
            options={'ordering': ['-visit_date', '-created_at'], 'verbose_name': 'Посещение врача', 'verbose_name_plural': 'Посещения врача'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название анализа'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='analyses/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='history.diseaserecord', verbose_name='Запись о болезни'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='result_text',
            field=models.TextField(blank=True, default='', verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='taken_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='date_of_illness',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала болезни'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='catalog.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='drugs',
            field=models.ManyToManyField(blank=True, related_name='records', to='catalog.drug', verbose_name='Лекарства'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='symptoms',
            field=models.TextField(blank=True, default='', verbose_name='Симптомы'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (если не выбрано заболевание)'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='diagnosis',
            field=models.TextField(blank=True, default='', verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='doctor_full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО врача'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='medicines_text',
            field=models.TextField(blank=True, default='', verbose_name='Лекарства'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='procedures_text',
            field=models.TextField(blank=True, default='', verbose_name='Процедуры'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_visits', to='history.diseaserecord', verbose_name='Запись о болезни'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='history.diseaserecord', verbose_name='Запись о болезни'),
        ),
    ]
