# Generated by Django 5.2.6 on 2026-05-03 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_analysis_options_alter_diseaserecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaserecord',
            name='subject_user',
            field=models.ForeignKey(blank=True, help_text='Если null — запись относится к владельцу (user).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_records_as_subject', to=settings.AUTH_USER_MODEL, verbose_name='Для кого запись (член семьи)'),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи (аккаунт)'),
        ),
    ]
