# Generated by Django 5.2.6 on 2026-05-08 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_diseaserecord_subject_user_alter_diseaserecord_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaserecord',
            name='subject_user',
            field=models.ForeignKey(blank=True, help_text='Если null — запись относится к владельцу (поле user).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_records_as_subject', to=settings.AUTH_USER_MODEL, verbose_name='Для кого запись (член семьи)'),
        ),
    ]
