# Generated by Django 5.2.6 on 2026-04-21 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating 0.00–5.00 (set via admin/backend later; default 0).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
