# Generated by Django 5.2.6 on 2026-04-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_disease_options_alter_drug_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='diseases',
            field=models.ManyToManyField(blank=True, help_text='Список заболеваний, которые можно лечить этим лекарством.', related_name='drugs', to='catalog.disease', verbose_name='Можно лечить'),
        ),
    ]
