# Generated by Django 5.2.6 on 2026-05-03 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_drug_treats_diseases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='Просмотрено')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='catalog.drug', verbose_name='Лекарство')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_view_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр лекарства',
                'verbose_name_plural': 'Просмотры лекарств',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='catalog_dru_user_id_773cf2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'drug'), name='uniq_user_drug_view')],
            },
        ),
    ]
