# Generated by GPT-5.2 on 2026-05-07

from django.db import migrations


def seed_helper_reference_data(apps, schema_editor):
    BodyPart = apps.get_model("catalog", "BodyPart")
    Symptom = apps.get_model("catalog", "Symptom")

    body_parts = [
        ("head", "Голова", 10),
        ("throat", "Горло", 20),
        ("chest", "Грудная клетка", 30),
        ("back", "Спина", 40),
        ("abdomen", "Живот", 50),
        ("pelvis", "Таз", 60),
        ("left_arm", "Левая рука", 70),
        ("right_arm", "Правая рука", 80),
        ("left_hand", "Левая кисть", 90),
        ("right_hand", "Правая кисть", 100),
        ("left_leg", "Левая нога", 110),
        ("right_leg", "Правая нога", 120),
        ("left_foot", "Левая стопа", 130),
        ("right_foot", "Правая стопа", 140),
        ("skin", "Кожа", 150),
    ]

    BodyPart.objects.bulk_create(
        [BodyPart(code=code, label=label, sort_order=sort_order) for code, label, sort_order in body_parts],
        ignore_conflicts=True,
    )

    symptoms = [
        ("Головная боль", "боль в голове;мигрень"),
        ("Зуд", "чешется;кожный зуд"),
        ("Отёк", "опухоль;припухлость"),
        ("Тошнота", "подташнивает"),
        ("Рвота", ""),
        ("Головокружение", "кружится голова"),
        ("Слабость", "упадок сил;усталость"),
        ("Озноб", "знобит"),
        ("Повышенная температура", "жар;лихорадка"),
        ("Боль в горле", "першение"),
        ("Кашель", "покашливание"),
        ("Насморк", "ринит;заложенность носа"),
        ("Одышка", "трудно дышать"),
        ("Боль в груди", ""),
        ("Боль в животе", "спазмы;рези"),
        ("Изжога", "жжение"),
        ("Диарея", "понос"),
        ("Запор", ""),
        ("Сыпь", "высыпания"),
        ("Боль в мышцах", "ломота"),
        ("Боль в суставах", ""),
        ("Боль в руке", ""),
        ("Боль в ноге", ""),
    ]

    Symptom.objects.bulk_create(
        [Symptom(name=name, aliases=aliases) for name, aliases in symptoms],
        ignore_conflicts=True,
    )


def unseed_helper_reference_data(apps, schema_editor):
    BodyPart = apps.get_model("catalog", "BodyPart")
    Symptom = apps.get_model("catalog", "Symptom")

    BodyPart.objects.filter(
        code__in=[
            "head",
            "throat",
            "chest",
            "back",
            "abdomen",
            "pelvis",
            "left_arm",
            "right_arm",
            "left_hand",
            "right_hand",
            "left_leg",
            "right_leg",
            "left_foot",
            "right_foot",
            "skin",
        ]
    ).delete()

    Symptom.objects.filter(
        name__in=[
            "Головная боль",
            "Зуд",
            "Отёк",
            "Тошнота",
            "Рвота",
            "Головокружение",
            "Слабость",
            "Озноб",
            "Повышенная температура",
            "Боль в горле",
            "Кашель",
            "Насморк",
            "Одышка",
            "Боль в груди",
            "Боль в животе",
            "Изжога",
            "Диарея",
            "Запор",
            "Сыпь",
            "Боль в мышцах",
            "Боль в суставах",
            "Боль в руке",
            "Боль в ноге",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_bodypart_symptom"),
    ]

    operations = [
        migrations.RunPython(seed_helper_reference_data, reverse_code=unseed_helper_reference_data),
    ]

