# Generated by Django 5.0.7 on 2026-05-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_reorder_body_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
