# Generated by Django 5.0.7 on 2026-08-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_drug_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="drug",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Снимите галочку, чтобы скрыть препарат (напр. мусорные импортированные записи).",
                verbose_name="Показывать в приложении",
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Название"),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(fields=["is_active", "name"], name="catalog_drug_active_name_idx"),
        ),
    ]
