# Generated by Django 5.0.7 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_drug_disease_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='Полный текст со спойлерами: общие сведения, причины, симптомы, лечение…', verbose_name='Подробное описание (разделы)'),
        ),
    ]
